Repository NicolasDuciaume/SYSC4806_Web_App, pull requests merged in 2022-04, with the labels that each got.

#71 68 switch login and registration to encrypted
  src/main/java/SYSC6/Project/Main_Controller.java
  src/main/java/SYSC6/Project/UserController.java
  src/main/java/SYSC6/Project/WebConfig.java
  src/main/resources/Javascript/Login_Script.js
  src/main/resources/Javascript/Register_Script.js
  src/main/resources/css/LoginStyle.css
  src/main/resources/css/styles.css
  src/main/resources/templates/Registration.html
  src/main/resources/templates/login_form.html
  src/main/resources/templates/user_portal.html
  src/test/java/SYSC6/Project/UserControllerTest.java
Labels: Sub-Feature

#74 Added the check to need at least 6 characters, a special character an…
  src/main/java/SYSC6/Project/UserController.java
  src/main/resources/Javascript/Register_Script.js
  src/main/resources/templates/Registration.html
Labels: Sub-Feature

#75 69 final update for login and resgistration
  src/main/java/SYSC6/Project/Login.java
  src/main/java/SYSC6/Project/Main_Controller.java
  src/main/java/SYSC6/Project/UserController.java
  src/main/java/SYSC6/Project/UserRepository.java
  src/main/java/SYSC6/Project/WebConfig.java
  src/main/resources/Images/login.jpg
  src/main/resources/Images/register.jpg
  src/main/resources/Javascript/Login_Script.js
  src/main/resources/Javascript/Register_Script.js
  src/main/resources/css/LoginStyle.css
  src/main/resources/css/styles.css
  src/main/resources/templates/Registration.html
  src/main/resources/templates/login_form.html
  src/main/resources/templates/user_portal.html
  src/test/java/SYSC6/Project/LoginTest.java
  src/test/java/SYSC6/Project/Main_ControllerTest.java
  src/test/java/SYSC6/Project/UserControllerTest.java
Labels: feature

#76 Lib Update
  src/main/resources/Javascript/bootstrap.js
  src/main/resources/Javascript/jquery.js
  src/main/resources/Javascript/popper.js
  src/main/resources/datatable/datatables.css
  src/main/resources/datatable/datatables.js
Labels: Sub-Feature

#61 User roles 22 part2
  pom.xml
  src/main/java/SYSC6/Project/Admin.java
  src/main/java/SYSC6/Project/Main_Controller.java
  src/main/java/SYSC6/Project/ProjectApplication.java
  src/main/java/SYSC6/Project/RoleType.java
  src/main/java/SYSC6/Project/WebConfig.java
  src/main/java/SYSC6/Project/sorting/Column.java
  src/main/java/SYSC6/Project/sorting/Direction.java
  src/main/java/SYSC6/Project/sorting/Order.java
  src/main/java/SYSC6/Project/sorting/Page.java
  src/main/java/SYSC6/Project/sorting/PageArray.java
  src/main/java/SYSC6/Project/sorting/PagingRequest.java
  src/main/java/SYSC6/Project/sorting/Search.java
  src/main/java/SYSC6/Project/user/User.java
  src/main/java/SYSC6/Project/user/UserController.java
  src/main/java/SYSC6/Project/user/UserRepository.java
  src/main/java/SYSC6/Project/user/UserUtil.java
  src/main/java/SYSC6/Project/user/userManagement/UserComparators.java
  src/main/java/SYSC6/Project/user/userManagement/UserPOJO.java
  src/main/java/SYSC6/Project/user/userManagement/UserRestController.java
  src/main/java/SYSC6/Project/user/userManagement/UserService.java
  src/main/resources/css/bootstrap.css
  src/main/resources/templates/admin_portal.html
  src/main/resources/templates/user_portal.html
  src/main/resources/templates/view_users.html
  src/main/resources/users.json
  src/test/java/SYSC6/Project/UserTest.java
Labels: feature, Ready For Code Review

#78 User roles 22 part3
  src/main/java/SYSC6/Project/user/UserController.java
  src/test/java/SYSC6/Project/UserControllerTest.java
Labels: Sub-Feature

#83 Delete User Portal
  src/main/java/SYSC6/Project/Main_Controller.java
  src/main/java/SYSC6/Project/ProjectApplication.java
  src/main/java/SYSC6/Project/WebConfig.java
  src/main/java/SYSC6/Project/user/UserController.java
  src/main/java/SYSC6/Project/user/UserRepository.java
  src/main/java/SYSC6/Project/user/userManagement/UserService.java
  src/main/resources/templates/confirm_delete.html
  src/main/resources/templates/user_portal.html
  src/test/java/SYSC6/Project/Main_ControllerTest.java
  src/test/java/SYSC6/Project/UserControllerTest.java
Labels: Ready For Code Review

#87 Polish
  src/main/java/SYSC6/Project/Main_Controller.java
  src/main/java/SYSC6/Project/sorting/Direction.java
  src/main/java/SYSC6/Project/user/Admin.java
  src/main/java/SYSC6/Project/user/RoleType.java
  src/main/java/SYSC6/Project/user/User.java
  src/main/java/SYSC6/Project/user/UserRepository.java
  src/main/java/SYSC6/Project/user/UserUtil.java
  src/main/java/SYSC6/Project/user/controllers/UserController.java
  src/main/java/SYSC6/Project/user/controllers/UserPortalController.java
  src/main/java/SYSC6/Project/user/userManagement/UserComparators.java
  src/main/java/SYSC6/Project/user/userManagement/UserPOJO.java
  src/main/java/SYSC6/Project/user/userManagement/UserRestController.java
  src/main/java/SYSC6/Project/user/userManagement/UserService.java
  src/main/java/SYSC6/Project/user/userManagement/sorting/Column.java
  src/main/java/SYSC6/Project/user/userManagement/sorting/Direction.java
  src/main/java/SYSC6/Project/user/userManagement/sorting/Order.java
  src/main/java/SYSC6/Project/user/userManagement/sorting/Page.java
  src/main/java/SYSC6/Project/user/userManagement/sorting/PageArray.java
  src/main/java/SYSC6/Project/user/userManagement/sorting/PagingRequest.java
  src/main/java/SYSC6/Project/user/userManagement/sorting/Search.java
  src/main/resources/templates/Registration.html
  src/main/resources/templates/view_users.html
  src/test/java/SYSC6/Project/AdminTest.java
  src/test/java/SYSC6/Project/UserControllerTest.java
  src/test/java/SYSC6/Project/UserTest.java
Labels: Polish

#88 Master heroku version
  src/main/java/SYSC6/Project/Main_Controller.java
  src/main/java/SYSC6/Project/sorting/Direction.java
  src/main/java/SYSC6/Project/user/Admin.java
  src/main/java/SYSC6/Project/user/RoleType.java
  src/main/java/SYSC6/Project/user/User.java
  src/main/java/SYSC6/Project/user/UserRepository.java
  src/main/java/SYSC6/Project/user/UserUtil.java
  src/main/java/SYSC6/Project/user/controllers/UserController.java
  src/main/java/SYSC6/Project/user/controllers/UserPortalController.java
  src/main/java/SYSC6/Project/user/userManagement/UserComparators.java
  src/main/java/SYSC6/Project/user/userManagement/UserPOJO.java
  src/main/java/SYSC6/Project/user/userManagement/UserRestController.java
  src/main/java/SYSC6/Project/user/userManagement/UserService.java
  src/main/java/SYSC6/Project/user/userManagement/sorting/Column.java
  src/main/java/SYSC6/Project/user/userManagement/sorting/Direction.java
  src/main/java/SYSC6/Project/user/userManagement/sorting/Order.java
  src/main/java/SYSC6/Project/user/userManagement/sorting/Page.java
  src/main/java/SYSC6/Project/user/userManagement/sorting/PageArray.java
  src/main/java/SYSC6/Project/user/userManagement/sorting/PagingRequest.java
  src/main/java/SYSC6/Project/user/userManagement/sorting/Search.java
  src/main/resources/Javascript/Login_Script.js
  src/main/resources/Javascript/Register_Script.js
  src/main/resources/templates/Registration.html
  src/main/resources/templates/admin_portal.html
  src/main/resources/templates/user_portal.html
  src/main/resources/templates/view_users.html
  src/test/java/SYSC6/Project/AdminTest.java
  src/test/java/SYSC6/Project/UserControllerTest.java
  src/test/java/SYSC6/Project/UserTest.java
Labels: Critical

#89 Heroku MasterVersion
  src/main/java/SYSC6/Project/Main_Controller.java
  src/main/java/SYSC6/Project/user/controllers/UserController.java
  src/main/java/SYSC6/Project/user/controllers/UserPortalController.java
  src/main/resources/Javascript/Login_Script.js
  src/main/resources/Javascript/Register_Script.js
  src/main/resources/templates/admin_portal.html
  src/main/resources/templates/user_portal.html
  src/main/resources/templates/view_users.html
Labels: Critical

#90 Heroku MasterVersion
  src/main/resources/templates/view_users.html
Labels: Critical

#91 Heroku
  src/main/java/SYSC6/Project/Main_Controller.java
  src/main/java/SYSC6/Project/WebConfig.java
  src/main/java/SYSC6/Project/user/controllers/UserController.java
  src/main/java/SYSC6/Project/user/controllers/UserPortalController.java
  src/main/resources/Javascript/Login_Script.js
  src/main/resources/Javascript/Register_Script.js
  src/main/resources/templates/admin_portal.html
  src/main/resources/templates/user_portal.html
  src/main/resources/templates/view_users.html
Labels: Critical
